import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy",
  description:
    "What MedAssist AI stores, where it is stored, what is sent to third-party AI providers, and what this deployment does not claim.",
};

const SECTIONS = [
  {
    id: "what-is-stored",
    title: "What is stored",
    body: [
      "In your account: your email address, display name, optional photo URL, optional default age and sex, and interface preferences.",
      "Per assessment: the symptoms you selected, the free text you typed, your answers to the follow-up questions, the history, medications and allergies you entered, and the structured analysis result.",
      "Per upload: the file itself, its size, its content type, a SHA-256 hash, a sanitised display name, and whether its text could be extracted.",
      "Audit records: what action happened, to which resource, and when. These deliberately contain no clinical content, no prompts and no document text.",
    ],
  },
  {
    id: "where-it-lives",
    title: "Where it lives",
    body: [
      "Medical information is stored in Google Firebase: Cloud Firestore for structured records and Cloud Storage for uploaded files.",
      "Storage objects are private. They are not given public URLs, and the bucket is not configured to allow unauthenticated reads. Previews are served through short-lived signed URLs generated only for the signed-in owner.",
      "Files are namespaced under users/{your-id}/{assessment-id}/{file-id}, and both Firestore and Storage rules enforce that a signed-in user can only read or write records whose owner id matches their own.",
    ],
  },
  {
    id: "what-leaves-the-browser",
    title: "What leaves your browser",
    body: [
      "Your file is uploaded to Firebase Storage.",
      "The text extracted from an uploaded PDF, or the text you paste, is sent to the OpenRouter API along with a prompt, so that a language model can transcribe or summarise it. A consent-style notice is not required by the architecture; instead, this page and the in-app privacy notes state plainly what is transmitted.",
      "If a vision-capable model is configured, an uploaded image is also sent to the OpenRouter API as base64 data.",
      "Your email address, display name and account identifiers are never included in any AI request.",
      "A best-effort redaction pass removes email addresses, phone numbers, IP addresses, common national-ID patterns and printed record numbers before text is sent. This is a courtesy layer, not a guarantee of de-identification, which is why we ask you not to upload unnecessary identifying information.",
    ],
  },
  {
    id: "retention",
    title: "Retention and deletion",
    body: [
      "There is no automatic expiry. Your data is kept until you delete it.",
      "Deleting an assessment deletes its uploads from Storage along with its Firestore records.",
      "Deleting a report removes the report record and immediately revokes any share link it generated.",
      "Deleting your account removes your profile, every assessment, every uploaded file, every report and every audit record, revokes your sessions and deletes the Firebase Authentication account.",
    ],
  },
  {
    id: "what-we-do-not-claim",
    title: "What this deployment does not claim",
    body: [
      "It does not claim HIPAA, GDPR or any other regulatory compliance. Compliance is a property of an entire deployment — including contracts with processors, access controls, incident procedures and hosting configuration — and cannot be established by application code alone.",
      "It does not claim to be HIPAA compliant, GDPR compliant, or certified to any standard.",
      "It does not claim clinical accuracy, diagnostic accuracy, or validation against any clinical dataset. The safety rule set in particular is an illustrative baseline that has not been clinically validated and is marked as such in the settings page.",
      "It does not claim that AI output is reliable. It is generated by a language model and can be incomplete or wrong.",
    ],
  },
  {
    id: "security-practices",
    title: "Security practices in this codebase",
    body: [
      "Authentication is handled by Firebase Authentication. Passwords are never seen by this application.",
      "The browser holds a Firebase token in memory; the server session is an httpOnly, Secure, SameSite=Lax cookie, so client-side script cannot read it.",
      "All AI requests are server-side. The OpenRouter API key is a server-only environment variable and is never bundled into client code.",
      "Files are validated on three axes: declared MIME type, file extension, and the magic number in the first bytes of the file. Extensions alone are never trusted.",
      "Uploads are size-capped per file and per assessment, and PDFs are never executed.",
      "Every AI response is validated against a Zod schema. If validation fails, one repair attempt is made; if that also fails, nothing is rendered. Malformed medical output is never displayed.",
      "Document and user text is delimited and explicitly declared as data before reaching a model, so instructions embedded in an uploaded report cannot change the system's behaviour.",
      "There is a per-endpoint rate limiter, and audit records are written for analysis runs, uploads, sharing changes and deletions.",
    ],
  },
  {
    id: "model-output",
    title: "Accuracy of AI output",
    body: [
      "MedAssist AI can produce incorrect output. Language models miss information, over-weight what is salient in the prompt, and can generate plausible-sounding detail that was never in the input.",
      "Where a value from a laboratory report is shown, it is validated against the source text and discarded if it cannot be located there.",
      "Image analysis is only performed when the configured model genuinely supports vision, and its output is labelled as an unverified visual description.",
      "Verify everything against your original documents, and have a qualified healthcare professional interpret them.",
    ],
  },
] as const;

export default function PrivacyPage() {
  return (
    <main id="main-content" className="mx-auto w-full max-w-3xl px-4 py-16 sm:px-6">
      <p className="eyebrow">Legal and technical</p>
      <h1 className="mt-3 text-3xl font-semibold tracking-tight text-ink sm:text-4xl">Privacy</h1>
      <p className="mt-4 text-pretty text-base leading-relaxed text-muted">
        Plainly: what is stored, where, what is transmitted to a third party, and what this
        deployment does not promise.
      </p>

      <div className="mt-10 space-y-8">
        {SECTIONS.map((section) => (
          <section key={section.id} id={section.id} className="scroll-mt-24">
            <h2 className="text-lg font-semibold tracking-tight text-ink">{section.title}</h2>
            <ul className="mt-3 space-y-2.5">
              {section.body.map((paragraph, index) => (
                <li key={index} className="flex gap-2.5 text-sm leading-relaxed text-muted">
                  <span aria-hidden="true" className="mt-2 size-1.5 shrink-0 rounded-full bg-brand" />
                  {paragraph}
                </li>
              ))}
            </ul>
          </section>
        ))}
      </div>

      <div className="mt-12 rounded-2xl border border-caution/30 bg-caution-soft/40 p-5">
        <p className="text-sm leading-relaxed text-ink">
          <strong className="font-semibold">Please avoid uploading unnecessary identifying
          information.</strong> If a report contains your name, address or national identifier, the
          redaction pass may not catch every instance. Remove the identifying header from a
          document before uploading it where you are able to.
        </p>
      </div>

      <p className="mt-8 text-sm text-muted">
        See also the{" "}
        <Link href="/disclaimer" className="font-medium text-brand underline underline-offset-4">
          medical disclaimer
        </Link>{" "}
        and the{" "}
        <Link href="/faq" className="font-medium text-brand underline underline-offset-4">
          FAQ
        </Link>
        .
      </p>
    </main>
  );
}