import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Medical disclaimer",
  description:
    "MedAssist AI is an automated decision-support tool for education. It is not a doctor, not a diagnostic device, and not a substitute for professional medical care.",
};

export default function DisclaimerPage() {
  return (
    <main id="main-content" className="mx-auto w-full max-w-3xl px-4 py-16 sm:px-6">
      <p className="eyebrow">Important</p>
      <h1 className="mt-3 text-3xl font-semibold tracking-tight text-ink sm:text-4xl">
        Medical disclaimer
      </h1>

      <div className="mt-8 space-y-6">
        <section className="glass rounded-3xl border-critical/30 p-6">
          <h2 className="text-base font-semibold tracking-tight text-ink">
            MedAssist AI is not a medical service
          </h2>
          <p className="mt-2 text-sm leading-relaxed text-muted">
            MedAssist AI is an automated decision-support tool intended for education and for
            organising information you already have. It is not a doctor. It is not a diagnostic
            device. It is not a medical record. It does not examine you, take a history, order
            tests, or prescribe treatment. It cannot replace a consultation with a qualified
            healthcare professional, and no part of its output should be treated as a clinical
            judgement.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold tracking-tight text-ink">
            It never makes a diagnosis
          </h2>
          <p className="mt-2 text-sm leading-relaxed text-muted">
            The application reports possible explanations. When it describes something, it says
            that the available information <em>may be consistent with</em> a condition,{" "}
            <em>could indicate</em> a finding, or is <em>a possible explanation that requires
            clinical evaluation</em>. It never says that you have a disease, because it cannot know
            that. Only a qualified professional who has examined you can determine a diagnosis.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold tracking-tight text-ink">
            It does not give medical advice or treatment
          </h2>
          <p className="mt-2 text-sm leading-relaxed text-muted">
            The application does not prescribe, recommend or dose any medication, and it does not
            advise on treatment. Its next steps are limited to categories such as contacting
            emergency services, seeking urgent care, booking an appointment, monitoring symptoms,
            gathering information and general self-care. Any question about what to take belongs
            with a qualified prescriber who has examined you.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold tracking-tight text-ink">
            Emergencies
          </h2>
          <p className="mt-2 text-sm leading-relaxed text-muted">
            If you believe you or someone else may be experiencing a medical emergency, contact
            your local emergency number or go to the nearest emergency department immediately. Do
            not wait for an assessment from this application, and do not rely on it to decide
            whether a situation is urgent. Symptoms that appear mild can deteriorate quickly, and
            this application has no way to observe that.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold tracking-tight text-ink">
            Limitations you should assume
          </h2>
          <ul className="mt-2 space-y-2.5">
            {[
              "The assessment is generated by a language model from information you supplied. It has not seen you and has spoken to no clinician.",
              "It cannot reliably interpret medical images. Where image description is offered, it is an unverified visual description, not a radiological report.",
              "It can omit relevant findings and can produce incorrect information. Verify everything against your original documents.",
              "It does not know your full medical history, your examination findings, or anything you did not tell it. Absence of a mention is not evidence of absence.",
              "The deterministic safety rules are an illustrative baseline and have not been clinically validated.",
            ].map((item) => (
              <li key={item} className="flex gap-2.5 text-sm leading-relaxed text-muted">
                <span aria-hidden="true" className="mt-2 size-1.5 shrink-0 rounded-full bg-brand" />
                {item}
              </li>
            ))}
          </ul>
        </section>

        <section>
          <h2 className="text-base font-semibold tracking-tight text-ink">Intended use</h2>
          <p className="mt-2 text-sm leading-relaxed text-muted">
            This application is intended to help you prepare for a conversation with a healthcare
            professional: to understand what your documents appear to show, to organise what you
            want to describe, and to arrive with better questions. That is the whole of its purpose.
            It is not intended for clinical decision-making by anyone, including the person using
            it and including clinicians.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold tracking-tight text-ink">Regulatory status</h2>
          <p className="mt-2 text-sm leading-relaxed text-muted">
            No claim of regulatory compliance is made. Whether a given deployment satisfies any
            particular medical-device regulation, privacy law or security standard depends on the
            full system and its operation, not on this application code. See the{" "}
            <Link href="/privacy" className="font-medium text-brand underline underline-offset-4">
              privacy page
            </Link>{" "}
            for detail.
          </p>
        </section>
      </div>

      <div className="mt-10 flex flex-wrap gap-3">
        <Link
          href="/assessment/new"
          className="inline-flex h-10 items-center rounded-full bg-brand px-5 text-sm font-medium text-white transition-colors hover:bg-brand-strong"
        >
          Start an assessment
        </Link>
        <Link
          href="/faq"
          className="inline-flex h-10 items-center rounded-full border border-line-strong px-5 text-sm font-medium text-ink transition-colors hover:bg-brand/5"
        >
          Read the FAQ
        </Link>
      </div>
    </main>
  );
}