/**
 * Report generation.
 *
 * Two things live here:
 *
 *  1. `buildReportSections` — a deterministic renderer that turns the validated
 *     assessment result into the printed/ downloadable report. It performs no
 *     model call at all: the report must faithfully reproduce exactly what was
 *     validated and stored, never a fresh improvisation.
 *
 *  2. `buildPractitionerBriefPrompt` — an optional, explicitly user-triggered
 *     stage that condenses the assessment into a short brief a person can read
 *     out or hand over at an appointment. Kept separate so the free-tier cost
 *     is only incurred when the user asks for it.
 */

import type { AssessmentResult, TriageResult } from "@/types/assessment";
import type { MedicalCase } from "@/types/medical";
import { PROMPT_VERSION } from "@/lib/ai/models";
import { urgencyPresentation } from "@/lib/medical/urgency";
import {
  ANTI_INJECTION,
  DISCLAIMER_LINE,
  SAFETY_RULES,
  SYSTEM_ROLE,
} from "@/lib/ai/prompts/safety";

export const REPORT_VERSION = PROMPT_VERSION;
export const PRACTITIONER_BRIEF_PROMPT_VERSION = "practitioner-brief-v1";

export const REPORT_DISCLAIMER =
  "This document was generated by MedAssist AI, an automated decision-support tool, from information " +
  "that the user entered and documents that the user uploaded. It is NOT a diagnosis, NOT a medical " +
  "record, and NOT a substitute for professional medical advice, examination, or testing. Some content " +
  "may be incomplete or incorrect. Every statement here — including any statement about what a " +
  "laboratory value means — must be independently verified against the original documents and " +
  "confirmed by a qualified healthcare professional who has examined the person. Do not use this " +
  "document as the basis for a treatment decision without clinical review. " +
  "IN AN EMERGENCY, contact your local emergency number or go to the nearest emergency department " +
  "immediately. Do not wait for, or rely on, this document. If the person's condition deteriorates, " +
  "seek medical care rather than relying on this document.";

export interface ReportSection {
  id: string;
  title: string;
  /** Rendered as paragraphs. */
  paragraphs: string[];
  /** Rendered as a bulleted list when present. */
  bullets: string[];
  /** Set when the section must be visually distinguished (e.g. urgency). */
  emphasis?: "normal" | "highlight" | "critical";
}

export interface ReportDocument {
  title: string;
  subtitle: string;
  generatedAt: string;
  sections: ReportSection[];
  disclaimer: string;
}

export interface ReportInput {
  assessmentId: string;
  reportTitle: string;
  createdAt: string;
  patientLabel: string;
  result: AssessmentResult;
  triage: TriageResult;
  /**
   * The case snapshot. Required for the factual sections — patient information,
   * presenting symptoms, relevant history — which restate what the user entered
   * rather than anything the model produced.
   */
  caseData: MedicalCase;
  /** Which categories of input were present, used for the provenance section. */
  evidenceSummary: string[];
  missingSummary: string[];
  modelLabel: string;
  rulesetVersion: string;
}

function clean(items: string[] | undefined): string[] {
  if (!items) return [];
  return items.map((i) => i.trim()).filter((i) => i.length > 0);
}

export function buildReportSections(input: ReportInput): ReportSection[] {
  const { result, triage, caseData } = input;
  const urgency = urgencyPresentation(result.urgency.level);
  const sections: ReportSection[] = [];

  /* ------------------------------------------------ Patient information --- */
  // Stated as facts, not inferences. "Not provided" is recorded explicitly
  // rather than left blank, so a reader can tell absence from omission.
  const patientFacts: string[] = [];
  patientFacts.push(
    caseData.demographics.age !== undefined
      ? `Age: ${caseData.demographics.age}`
      : "Age: not provided",
  );
  patientFacts.push(
    caseData.demographics.sex
      ? `Sex: ${caseData.demographics.sex.replace(/_/g, " ")}`
      : "Sex: not provided",
  );
  patientFacts.push(`Account: ${input.patientLabel}`);

  sections.push({
    id: "patient_information",
    title: "Patient Information",
    paragraphs: [
      "The details below were entered by the account holder. Nothing here has been verified against an identity document, and no identifying information is included in this report.",
    ],
    bullets: patientFacts,
    emphasis: "normal",
  });

  /* ------------------------------------------------ Presenting symptoms --- */
  sections.push({
    id: "presenting_symptoms",
    title: "Presenting Symptoms",
    paragraphs:
      caseData.symptoms.length === 0
        ? ["No symptoms were recorded. Any description below was taken from the free text."]
        : ["Recorded by the person completing this assessment, in their own words."],
    bullets:
      caseData.symptoms.length > 0
        ? caseData.symptoms.map((symptom) => {
            const details = [symptom.duration, symptom.severity].filter(Boolean).join(", ");
            return details.length > 0 ? `${symptom.name} (${details})` : symptom.name;
          })
        : caseData.freeText.trim().length > 0
          ? [caseData.freeText.trim().slice(0, 600)]
          : [],
    emphasis: "normal",
  });

  /* --------------------------------------------------- Relevant history -- */
  const historyBullets: string[] = [];
  if (caseData.medicalHistory.length > 0) {
    for (const entry of caseData.medicalHistory) {
      const status = entry.status ? ` (${entry.status})` : "";
      const note = entry.note ? ` — ${entry.note}` : "";
      historyBullets.push(`${entry.condition}${status}${note}`);
    }
  }
  if (caseData.medications.length > 0) {
    historyBullets.push(`Medications reported: ${caseData.medications.join("; ")}`);
  }
  if (caseData.allergies.length > 0) {
    historyBullets.push(`Allergies reported: ${caseData.allergies.join("; ")}`);
  }

  const lifestyleEntries = Object.entries(caseData.lifestyle).filter(([, value]) =>
    typeof value === "string" ? value.trim().length > 0 : Boolean(value),
  );
  for (const [key, value] of lifestyleEntries) {
    if (typeof value === "string") {
      historyBullets.push(`${key.replace(/([A-Z])/g, " $1").toLowerCase()}: ${value}`);
    }
  }

  if (caseData.answers.length > 0) {
    historyBullets.push("Follow-up answers given:");
    for (const answer of caseData.answers) {
      historyBullets.push(`  Q: ${answer.question} — A: ${answer.answer}`);
    }
  }

  sections.push({
    id: "relevant_history",
    title: "Relevant History",
    paragraphs: [
      historyBullets.length === 0
        ? "No medical history, medications, allergies or lifestyle information were provided."
        : "Self-reported. Not verified against any clinical record, and potentially incomplete.",
    ],
    bullets: historyBullets,
    emphasis: "normal",
  });

  /* ---------------------------------------------------------- Summary ---- */
  sections.push({
    id: "summary",
    title: "Overall Summary",
    paragraphs: [result.summary],
    bullets: [],
    emphasis: "normal",
  });

  sections.push({
    id: "urgency",
    title: "Risk / Urgency",
    paragraphs: [
      `${urgency.label} — ${urgency.description}`,
      result.urgency.reason,
      triage.escalated
        ? "Note: the urgency shown here was raised by the application's deterministic safety rules, independently of the AI-generated assessment."
        : "Note: no deterministic safety rule was triggered for this case.",
      // Which rules fired belongs in the urgency section, not only in the
      // appendix: this is the part a reader acts on.
      `Safety rules triggered: ${
        triage.firedRules.length > 0 ? triage.firedRules.join(", ") : "none"
      } (ruleset ${input.rulesetVersion}).`,
    ],
    bullets: clean(result.redFlags.map((f) => `${f.flag} — ${f.why}`)),
    emphasis: result.urgency.level === "EMERGENCY" ? "critical" : "highlight",
  });

  sections.push({
    id: "key_findings",
    title: "Key Findings",
    paragraphs: [],
    bullets: result.keyFindings.map((f) => `${f.title} (source: ${f.source.replace(/_/g, " ")}) — ${f.detail}`),
    emphasis: "normal",
  });

  sections.push({
    id: "symptom_analysis",
    title: "Symptom Analysis",
    paragraphs: [],
    bullets: result.symptomAnalysis.map(
      (s) =>
        `${s.symptom}: ${s.interpretation}${s.severityNote ? ` Severity: ${s.severityNote}.` : ""}${
          s.durationNote ? ` Duration: ${s.durationNote}.` : ""
        }`,
    ),
    emphasis: "normal",
  });

  if (result.documentFindings.length > 0) {
    sections.push({
      id: "documents",
      title: "Uploaded Documents and Their Findings",
      paragraphs: [
        "The following were extracted from documents the user uploaded. Values are reproduced as printed in the source document.",
      ],
      bullets: result.documentFindings,
      emphasis: "normal",
    });
  }

  if (result.imagingObservations.length > 0) {
    sections.push({
      id: "imaging",
      title: "Imaging Information",
      paragraphs: [
        "The observations below are AI-generated descriptions of what appeared to be visible in the uploaded image. They are not radiological interpretations and no original study has been reviewed.",
      ],
      bullets: result.imagingObservations,
      emphasis: "normal",
    });
  }

  sections.push({
    id: "possible_explanations",
    title: "Possible Explanations",
    paragraphs: [
      "These are possible explanations, not confirmed diagnoses. They are listed to help the user prepare questions for a healthcare professional, and each must be confirmed or excluded by clinical assessment and appropriate testing.",
    ],
    bullets: result.possibleExplanations.map(
      (e) =>
        `${e.rank}. ${e.explanation} — Why it may fit: ${e.whyItMayFit.join("; ")}.${
          e.whatWouldTestIt.length > 0 ? ` What would confirm or exclude it: ${e.whatWouldTestIt.join("; ")}.` : ""
        } ${e.confidenceNote}`,
    ),
    emphasis: "normal",
  });

  sections.push({
    id: "next_steps",
    title: "Recommended Next Steps",
    paragraphs: [
      "MedAssist AI does not prescribe, recommend or dose any medication. Treatment decisions belong entirely with a qualified prescriber.",
    ],
    bullets: result.recommendedNextSteps.map((step) => {
      const timeframe = `[${step.timeframe.replace(/_/g, " ")}] ${step.step}`;
      return step.rationale ? `${timeframe} — ${step.rationale}` : timeframe;
    }),
    emphasis: "normal",
  });

  sections.push({
    id: "clinician_questions",
    title: "Questions to Discuss With a Healthcare Professional",
    paragraphs: [],
    bullets: result.questionsForClinician,
    emphasis: "normal",
  });

  sections.push({
    id: "evidence",
    title: "Information That Informed This Assessment",
    paragraphs: [
      "Categories of information that contributed to the output above:",
    ],
    bullets: clean(input.evidenceSummary),
    emphasis: "normal",
  });

  if (input.missingSummary.length > 0) {
    sections.push({
      id: "missing",
      title: "Information Not Available",
      paragraphs: ["The following was not provided and its absence limits this assessment:"],
      bullets: clean(input.missingSummary),
      emphasis: "normal",
    });
  }

  sections.push({
    id: "limitations",
    title: "AI Limitations",
    paragraphs: [
      "The limitations below apply to every MedAssist AI output and are not specific to this case.",
    ],
    bullets: result.limitations,
    emphasis: "highlight",
  });

  sections.push({
    id: "provenance",
    title: "Provenance and Audit Information",
    paragraphs: [],
    bullets: [
      `Assessment reference: ${input.assessmentId}`,
      `Generated at: ${input.createdAt}`,
      `Language model: ${input.modelLabel}`,
      `Prompt version: ${REPORT_VERSION}`,
      `Deterministic triage ruleset version: ${input.rulesetVersion}`,
      `Safety rules triggered: ${triage.firedRules.length > 0 ? triage.firedRules.join(", ") : "none"}`,
      `Urgent level raised by safety rules: ${triage.escalated ? "yes" : "no"}`,
    ],
    emphasis: "normal",
  });

  return sections;
}

export function buildReportDocument(input: ReportInput): ReportDocument {
  return {
    title: input.reportTitle,
    subtitle: `AI-Assisted Health Assessment — ${input.patientLabel}`,
    generatedAt: input.createdAt,
    sections: buildReportSections(input),
    disclaimer: REPORT_DISCLAIMER,
  };
}

/* ------------------------------------------------------------------ *
 * Optional practitioner brief (explicit user action, one extra call)
 * ------------------------------------------------------------------ */

export interface PractitionerBrief {
  headline: string;
  chronology: string;
  keyPoints: string[];
  openQuestions: string[];
}

export function buildPractitionerBriefPrompt(
  input: ReportInput,
  seed: string,
): string {
  const { result, triage } = input;
  const urgency = urgencyPresentation(result.urgency.level);

  const body = `## Task

Condense this assessment into a brief a person can hand to, or read out to, a healthcare
professional at an appointment.

This is a communication aid. It is not a diagnosis and must be framed as the patient's own
account, not as clinical conclusions.

## Output

Return JSON with exactly these keys:

{
  "headline": "one sentence, at most 200 characters, describing what the person is experiencing in their own terms",
  "chronology": "one paragraph, at most 600 characters, laying out the time course of the problem",
  "keyPoints": ["at most 6 short factual points the clinician most needs to hear"],
  "openQuestions": ["at most 5 questions the patient should ask the clinician"]
}

Constraints:
- Report only what is in the input. Invent nothing.
- No medication names, no doses, no test orders, no treatment advice.
- No diagnostic language. Use "may be consistent with", "reports", "has noticed".
- keyPoints must be things the patient experienced or documents show, not your analysis.
- openQuestions are for the patient to ask, not instructions to the clinician.

## Input

Patient information:
- Age: ${input.caseData.demographics.age ?? "not provided"}
- Sex: ${input.caseData.demographics.sex ?? "not provided"}

Symptoms reported by the patient:
${input.caseData.symptoms.map((s) => `- ${s.name}${s.duration ? ` (duration: ${s.duration})` : ""}${s.severity ? ` (severity: ${s.severity})` : ""}`).join("\n") || "- none recorded"}

Current urgency level: ${urgency.label}
Deterministic safety layer raised urgency: ${triage.escalated ? "yes" : "no"}
Red flags identified: ${result.redFlags.length > 0 ? result.redFlags.map((f) => f.flag).join("; ") : "none"}

Symptoms:
${result.symptomAnalysis.map((s) => `- ${s.symptom}: ${s.interpretation}`).join("\n") || "- none recorded"}

Key findings:
${result.keyFindings.map((f) => `- ${f.title}: ${f.detail}`).join("\n") || "- none recorded"}

Document findings:
${result.documentFindings.join("; ") || "- none recorded"}

Questions already suggested for the clinician:
${result.questionsForClinician.join("; ") || "- none"}`;

  return [
    SYSTEM_ROLE,
    SAFETY_RULES,
    ANTI_INJECTION,
    "You write a short patient-communication brief. You never diagnose and you never prescribe. Return only JSON.",
    body,
    DISCLAIMER_LINE,
    `nonce="${seed}"`,
  ].join("\n\n");
}